--[[
	=====================================================================
	Addon		: [DLTX] Activated Charcoal
	Link:		: https://www.moddb.com/mods/stalker-anomaly/addons/dltx-activated-charcoal/
	Author		: TosoxDev
	Credits		: Igigog, Arti
	Last Edit	: 16.01.2023
	=====================================================================
--]]

local options = {
	["opt_loot_coefficient"]		= 1.0,
	["opt_trader_restock_amount"]	= 3.0,
	["opt_save_uninstall"]			= false
}

--[[
	=====================================================================
	MCM
	=====================================================================
--]]

function delete_addon_items()
	for i = 1, 65534 do
		local obj = alife_object(i)
		if obj then
			local obj_name = obj:name()
			if string.match(obj_name, "drug_charcoal") then
				alife_release(obj)
			end
		end
	end
end

function on_option_change()
	options["opt_loot_coefficient"] = drug_charcoal_mcm.get_config("loot_coefficient")
	options["opt_trader_restock_amount"] = drug_charcoal_mcm.get_config("trader_restock_amount")
	options["opt_save_uninstall"] = drug_charcoal_mcm.get_config("save_uninstall")
	
	if options["opt_save_uninstall"] and level.present() then
		delete_addon_items()
		drug_charcoal_mcm.set_config("save_uninstall", false)
	end
end

function actor_on_first_update()
	on_option_change()
end

--[[
	=====================================================================
	Item autoinject
	=====================================================================
--]]

function trader_inject_drug_charcoal(npc)
    local is_medic = trader_autoinject.get_trader_type(npc) == trader_autoinject.MEDIC
    if is_medic then
        trader_autoinject.spawn_items(npc, { ["drug_charcoal"] = options["opt_trader_restock_amount"] }, true)
    end
end

TraderAuto = trader_autoinject.update
function trader_autoinject.update(npc)
    TraderAuto(npc)
    trader_inject_drug_charcoal(npc)
end

local rank_table = {
	["novice"]			= 0.09,
	["trainee"]			= 0.08,
	["experienced"]		= 0.06,
	["professional"]	= 0.05,
	["veteran"]			= 0.05,
	["expert"]			= 0.04,
	["master"]			= 0.03,
	["legend"]			= 0.03,
}

function loot_inject_drug_charcoal(npc, npc_rank)
	local max_uses = SYS_GetParam(2, "drug_charcoal", "max_uses", 1)
	local do_uses = math.random(max_uses)
	local chance = (rank_table[npc_rank] or 0.1) * options["opt_loot_coefficient"]
	if math.random() < chance then
		alife_create_item("drug_charcoal", npc, { ["uses"] = do_uses })
	end
end

SpawnCosmetics = death_manager.spawn_cosmetics
function death_manager.spawn_cosmetics(npc, npc_id, npc_comm, npc_rank, visual, rand_condition)
    SpawnCosmetics(npc, npc_id, npc_comm, npc_rank, visual, rand_condition)
    loot_inject_drug_charcoal(npc, npc_rank)
end

--[[
	=====================================================================
	Register script callbacks
	=====================================================================
--]]

function on_game_start()
	RegisterScriptCallback("on_option_change", on_option_change)
	RegisterScriptCallback("actor_on_first_update", actor_on_first_update)
end
